version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: opencats-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: opencats
      MYSQL_USER: opencats
      MYSQL_PASSWORD: opencats
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 30

  web:
    build: .
    container_name: opencats-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      CATS_DB_HOST: db
      CATS_DB_NAME: opencats
      CATS_DB_USER: opencats
      CATS_DB_PASS: opencats
    volumes:
      - cats_files:/var/www/html/attachments

volumes:
  db_data:
  cats_files:
