version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENCATS_REPO: ${OPENCATS_REPO}
        OPENCATS_REF: ${OPENCATS_REF}
    depends_on:
      - db
    ports:
      - "8080:80"   # En Coolify puedes ajustar el mapeo/puerto público
    networks:
      - opencats
    restart: unless-stopped
    volumes:
      - opencats_uploads:/var/www/html/attachments

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - opencats
    restart: unless-stopped

networks:
  opencats:

volumes:
  db_data:
  opencats_uploads:
