version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENCATS_REPO: ${OPENCATS_REPO}
        OPENCATS_REF: ${OPENCATS_REF}
    container_name: opencats-web
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      # No son obligatorias para OpenCATS, pero útiles si haces healthchecks o scripts
      APP_ENV: production
    volumes:
      - opencats-www:/var/www/html

  db:
    image: mariadb:10.6
    container_name: opencats-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - opencats-db:/var/lib/mysql

volumes:
  opencats-db:
  opencats-www:
