version: "3.8"

services:
  web:
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    # Puedes dejar esta línea para pruebas por IP: http://TU_IP:8088/
    ports:
      - "${HOST_HTTP_PORT:-8088}:80"
    networks:
      - coolify

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - coolify

volumes:
  db-data:

networks:
  coolify:
    external: true
    name: coolify
