version: "3.9"

services:
  db:
    image: mariadb:10.6
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-opencats}
      MYSQL_USER: ${MYSQL_USER:-opencats}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?set MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?set MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - app
      - app_internal

  web:
    build:
      context: .
      args:
        OPENCATS_REPO: ${OPENCATS_REPO:-https://github.com/opencats/OpenCATS.git}
        OPENCATS_REF: ${OPENCATS_REF:-master}
    depends_on:
      db:
        condition: service_healthy

    # Traefik (Coolify proxy). No toca puertos del host.
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify

      # HTTP -> redirección a HTTPS
      - traefik.http.routers.opencats.rule=Host(`opencats.inxeniux.com.mx`)
      - traefik.http.routers.opencats.entrypoints=http
      - traefik.http.routers.opencats.middlewares=opencats-redirect
      - traefik.http.routers.opencats.service=opencats
      - traefik.http.middlewares.opencats-redirect.redirectscheme.scheme=https

      # HTTPS con ACME de Coolify
      - traefik.http.routers.opencats-sec.rule=Host(`opencats.inxeniux.com.mx`)
      - traefik.http.routers.opencats-sec.entrypoints=https
      - traefik.http.routers.opencats-sec.tls.certresolver=letsencrypt
      - traefik.http.routers.opencats-sec.service=opencats

      # Puerto interno del contenedor
      - traefik.http.services.opencats.loadbalancer.server.port=80

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

    # Persistencia de adjuntos/subidas
    volumes:
      - attachments:/var/www/html/attachments
      - uploads:/var/www/html/upload

    restart: unless-stopped
    networks:
      - coolify
      - app
      - app_internal

networks:
  # Red de Traefik de Coolify (ya existe)
  coolify:
    external: true
    name: coolify
  # Redes privadas del proyecto
  app:
    driver: bridge
  app_internal:
    internal: true

volumes:
  db_data:
  attachments:
  uploads:
