version: "3.8"

services:
  web:
    build:
      context: .
      # sin args ni environment aquí
    ports:
      - "${HOST_HTTP_PORT:-8088}:80"   # mapea el puerto desde Coolify
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
