version: "3.8"

networks:
  coolify:
    external: true

volumes:
  db_data: {}

services:
  db:
    image: mysql:5.7
    # OJO: Coolify puede ignorar container_name al correr, no pasa nada.
    container_name: opencats-db
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: opencats
      MYSQL_USER: opencats
      MYSQL_PASSWORD: "Trapeador0925"
      MYSQL_ROOT_PASSWORD: "Trapeador0925"
      TZ: America/Mexico_City
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pTrapeador0925"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 60s

  web:
    # Si tu repo tiene Dockerfile que compila OpenCATS, deja build: .
    # Si no, puedes cambiar por: image: opencats/opencats:latest
    build: .
    container_name: opencats-web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: opencats
      DB_USER: opencats
      DB_PASS: "Trapeador0925"
      TZ: America/Mexico_City
    expose:
      - "80"
    networks:
      - coolify
    labels:
      # Habilita Traefik y dile en qué red hablar con el contenedor
      - traefik.enable=true
      - traefik.docker.network=coolify

      # Puerto interno del servicio (OpenCATS sirve en 80 dentro del contenedor)
      - traefik.http.services.opencats.loadbalancer.server.port=80

      # Router HTTP → HTTPS (Coolify ya añade reglas si pones el dominio,
      # pero lo dejamos explícito por si acaso)
      - traefik.http.routers.opencats.rule=Host(`opencats.inxeniux.com.mx`)
      - traefik.http.routers.opencats.entrypoints=http,https
      - traefik.http.routers.opencats.tls=true
      - traefik.http.routers.opencats.tls.certresolver=letsencrypt

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 60s
