version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "${HOST_HTTP_PORT:-8088}:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - traefik.docker.network=coolify   # fuerza a Traefik a usar esa red

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - coolify

volumes:
  db_data:

networks:
  coolify:
    external: true
    name: coolify
