version: "3.8"

networks:
  coolify:
    external: true

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: opencats
      MYSQL_USER: opencats
      MYSQL_PASSWORD: Trapeador0925
      MYSQL_ROOT_PASSWORD: Trapeador0925
      TZ: America/Mexico_City
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pTrapeador0925"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 60s
    networks:
      - coolify

  web:
    # usa TU Dockerfile del repo
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: opencats
      DB_USER: opencats
      DB_PASS: Trapeador0925
      TZ: America/Mexico_City
    expose:
      - "80"         # Traefik consumirá este puerto interno
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.services.opencats.loadbalancer.server.port=80"

      # HTTPS (router principal)
      - "traefik.http.routers.opencats.rule=Host(`opencats.inxeniux.com.mx`)"
      - "traefik.http.routers.opencats.entrypoints=https"
      - "traefik.http.routers.opencats.tls.certresolver=letsencrypt"

      # HTTP -> redirección a HTTPS
      - "traefik.http.routers.opencats-http.rule=Host(`opencats.inxeniux.com.mx`)"
      - "traefik.http.routers.opencats-http.entrypoints=http"
      - "traefik.http.routers.opencats-http.middlewares=opencats-https-redirect"
      - "traefik.http.middlewares.opencats-https-redirect.redirectscheme.scheme=https"
    networks:
      - coolify

volumes:
  db_data: {}
