services:
  web:
    # ...
    networks:
      - ss4cko8gk0go880ko8sgkkgs_internal
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.services.opencats.loadbalancer.server.port=80

      # HTTP (opcional, sólo para redirigir)
      - traefik.http.routers.opencats.rule=Host(`opencats.inxeniux.com.mx`)
      - traefik.http.routers.opencats.entrypoints=http
      - traefik.http.middlewares.opencats-redirect.redirectscheme.scheme=https
      - traefik.http.routers.opencats.middlewares=opencats-redirect

      # HTTPS
      - traefik.http.routers.opencats-secure.rule=Host(`opencats.inxeniux.com.mx`)
      - traefik.http.routers.opencats-secure.entrypoints=https
      - traefik.http.routers.opencats-secure.tls=true
      - traefik.http.routers.opencats-secure.tls.certresolver=coolify  # o el que tengas en tu proxy

networks:
  ss4cko8gk0go880ko8sgkkgs_internal:
    driver: bridge
  coolify:
    external: true
